### ISSUE TITLE
Collection of Record Ideas

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-plans#16]
Over time we have collected quite a few ideas of how to improve records. Here they are all in one place, so we can figure out a coherent design:
- https://github.com/elm-lang/elm-compiler/issues/985 - remove extension and deletion
- https://github.com/elm-lang/elm-compiler/issues/842 - allow more JS-ish style for closing }
- https://github.com/elm-lang/elm-compiler/issues/635 - allow qualified records in update syntax
- https://github.com/elm-lang/elm-compiler/issues/537 - allow arbitrary expressions in update syntax

**Comment by Warry** [comment]
In the paper that @evancz linked in the Records announcement (http://research.microsoft.com/pubs/65409/scopedlabels.pdf) there were things like this : 

```
origin = {x = 0 | {y = 0 | {}}}
```

In order to compose records very freely using the pipe (a bit like _.extend in underscore?), I'd innocently add this to the debate without having any idea of the consequences in the actual implementation.

**Comment by jvoigtlaender** [comment]
Close this in favor of https://github.com/elm-lang/elm-compiler/issues/1068?

**Comment by jvoigtlaender** [comment]
Close this in favour of https://github.com/elm-lang/elm-compiler/issues/1375 now?

Because this issue here is still linked to, from https://github.com/elm-lang/elm-compiler/issues/635#issuecomment-128213965, but is not actually the current place anymore where this stuff is tracked.

**Comment by evancz** [comment]
This repo is not in use anymore. https://github.com/elm-lang/elm-compiler/issues/1375 takes precedence
