### ISSUE TITLE
centralized cache for elm packages

### ISSUE THREAD

**Issue by michaelglass** [elm-lang/elm-plans#20]
I have two problems that I believe might be solved with a centralized cache of downloaded packages:
1. elm-make spends tons of time downloading common libs that other repos have already downloaded
2. elm-make doesn't work offline / fails whenever github has trouble

**Comment by rtfeldman** [comment]
+1 - note that this would also want to be versioned on a per-compiler-version basis.

**Comment by mgold** [comment]
It's a great idea, but can we get a better writeup please?

**Comment by evancz** [comment]
This makes sense to me, seems like a solid idea.

@rtfeldman, the packages are all code artifacts that have an elm-version constraint, so what version of the compiler does not really add anything. If you are thinking of pre-compiling code, I don't think that's such a good idea. Depending on how the constraints get solved, there are different ways to build the same library. So I'm gonna say pre-compilation is not part of this proposal and should not be. It has problems and we should think about it after the basics are done here (so in a separate thing in the future)

I read this as:
- make a directory in `.elm/` which already exists
- next to `.elm/repl/` have `.elm/package/` that holds a bunch of stuff in the same style as `elm-stuff/packages/`

Only time this will mess up is if there is some concept of unpublishing. Maybe we can have a message on the server, so that if the server is reachable, we can figure out any changes that need to happen to the cache.

**Comment by rtfeldman** [comment]
Good point! I hadn't thought of that.

**Comment by evancz** [comment]
I'm in the process of closing this repo down. This idea is good. It may make sense to add it to https://github.com/elm-lang/projects but at the same time, it kind of does not. Either way, I have it on my personal todo list and it'll happen next time I touch elm-package.

Thanks for suggesting this!

**Comment by muelli** [comment]
what happened to this proposal?  Is there a cache now?
