### ISSUE TITLE
Proposal: Compile-time error for (function1 == function2)

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-plans#9]
## Proposed Change

If you attempt to call `==` passing two functions, instead of a runtime error you get a compile-time error similar to what you get if you call `<` passing two functions.

Currently the compile-time error message for trying to compare incomparable things is:

```
Note: comparable types include Int, Float, Char, String, lists, and tuples.
```

The current runtime exception for comparing functions is:

```
Equality error: general function equality is undecidable, and therefore, unsupported
```

The proposed compile-time error message for trying to test equality of functions would be:

```
The right argument of (==) is causing a type mismatch.

7|   fn1 == fn2

Note: functions cannot be compared using == because general function equality
is undecidable.

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    nonfunction

    a -> a
```

This would be a breaking change...but in a welcome way!
## Motivation

One of Elm's great benefits is minimizing runtime exceptions. This is one of the few remaining cases where a runtime exception during normal execution (that is, the system didn't run out of resources) can occur, but where having a compile-time error instead would be essentially all upside and no downside.

**Comment by mgold** [comment]
<s>Unreserved support</s> (see below). Can we also do this for signal types?

**Comment by jvoigtlaender** [comment]
A pragmatic alternative: https://github.com/elm-lang/core/pull/213.

Enforcing by the compiler that functions cannot be checked for equality would necessitate to introduce a concept like `equatable` analogous to `comparable`, and some `core` functions would need to get more restricted types. For example, we would then need to have

``` elm
Signal.dropRepeats : Signal equatable -> Signal equatable
```

instead of

``` elm
Signal.dropRepeats : Signal a -> Signal a
```

**Comment by mgold** [comment]
Jeff: I'd rather have an undecidable operation fail at runtime than tell me `(\a -> a) == identity` is false.

I thought about this a little more, and one problem is that non-equatability is _compositional_. For example,

``` elm
type alias SimpleAnimation = {
    start : Time,
    duration : Time,
    ease : Float -> Float,
 }
```

(Aside: optional commas make that look really nice.) Values of this type are also not equatable. Like comparable, any container must contain only equatable values for it to be equatable. I don't see us being able to track that without a lot of overhead as Jeff suggests. And it might not be so bad, seeing as how only `(==)`, `(/=)`, and `Signal.dropRepeats` would have to talk about `equatable` params.

There are a few other options, less comprehensive and not consistent with `comparable` and `appendable`, but which may lessen the programmer or compiler overhead.
- Don't worry about composition. This means you will still get runtime errors from equating two `SimpleAnimation`s but at least you catch the errors from equating functions or signals directly.
- Instead of writing `equatable` in the type, have some sort of declaration afterwards, a bit like how we do infix operators. `equatable a (==)` would mean that "the type variable `a` must be equatable in `(==)`. I think this would be most useful for library writes who need to use equality in many functions and doesn't want to have `equatable` everywhere.
- Don't make an "I require equatable things" declaration possible at all. Special-case the three functions that need it (above).

We'd also need to ensure that `comparable`, `appendable`, and `number` all implied `equatable`. At this point we're reinventing type classes. So maybe grab the low hanging fruit?

**Comment by rtfeldman** [comment]
Great points...I hadn't considered the implication of composing non-equatable things. Clearly this is not as low-hanging fruit as I'd thought!

**Comment by jvoigtlaender** [comment]
Max, concerning your ideas about avoiding something like `equatable` (by special-casing the "only three functions that need it", or via other means):

In such a world, if I write this function:

``` elm
f xs = case xs of
  (x:y:zs) -> x==y && f zs
  _        -> True
```

what type does it have?

If it is `f : List a -> Bool`, you might as well give up the whole "checking for function equality testing at compile time" idea, because I can then pass `[identity, identity]` to that function.

There is no easy trick here. To reliably avoid `==` on functions, in a way that works with modules etc., you _need_ something like an `Eq` type class, or `equatable` constraints, tracked by the type checker throughout the whole program...

**Comment by jvoigtlaender** [comment]
About "I'd rather have an undecidable operation fail at runtime than tell me (\a -> a) == identity is false", which I assume was addressed to me, though I'm not Jeff: Note that at current Elm will say "yes" to `identity == identity`, but behave differently for `(\a -> a) == identity`. So the semantic difference you don't want to be observable is already observable.

**Comment by mgold** [comment]
Yup, not Jeff, sorry Janis. And... _sigh_ yeah. Like Richard said, it's not a low-hanging fruit after all.

**Comment by rtfeldman** [comment]
I feel like this has been sufficiently discussed that the original proposal doesn't seem like a good idea anymore. I'm going to close this, but if someone else wants to propose a different alternative, feel free. :)
